### ISSUE TITLE
Fedora 36: Nvidia kernel module missing, falling back to nouveau

### ISSUE THREAD

**Issue by susukin0** [YurinDoctrine/ultra-gaming-setup-wizard#2]
OS: Fedora Linux 36 (Workstation Edition) x86_64 
Kernel: 5.18.3-xm1.0.fc36.x86_64 
CPU: Intel i5-10300H (8) @ 4.500GHz 
GPU: NVIDIA 01:00.0 NVIDIA Corporation TU117M 
GPU: Intel CometLake-H GT2 [UHD Graphics] 

when rebooting after script is done, i got Nvidia kernel module error on load and hear a loud beep sound soon after that.

tried to fix it by removing all nvidia dependencies:
sudo dnf remove *nvidia*

and then;
sudo dnf install akmod-nvidia-470xx

**Comment by YurinDoctrine** [comment]
Thank you for issuing this, you can now create a pull request under [this line](https://github.com/YurinDoctrine/ultra-gaming-setup-wizard/blob/69cd6aef9fe083d54183db219ab2009470a64354/ultra-gaming-setup-wizard.sh#L331).
