### ISSUE TITLE
Script to rollback all  the changes this made

### ISSUE THREAD

**Issue by Loskoss** [YurinDoctrine/ultra-gaming-setup-wizard#3]
OS-fedora 37
Kernel-6.0.11
CPU: Intel i5-10750H @ 5.00GHz
GPU: NVIDIA RTX 2060.

Hey, I ran this script and sadly my distro is kind of broken now so I would really appreciate if you can provide a script to rollback all the changes made, I also chose the secure Linux option can you please guide me to revert all the changes here as well thanks a lot.

**Comment by Loskoss** [comment]
for secure linux as well thanks a lot.

**Comment by YurinDoctrine** [comment]
If you can still access to the system try cleaning /etc/environment and remove nvidia package that I provided in thia script.

**Comment by Loskoss** [comment]
yeah  i was able to access it so i cleaned the environment file and when i try to remove the nvidia packages i get this error 
![image](https://user-images.githubusercontent.com/104411772/205880846-830f855f-181c-47be-ac69-2263aa433b22.png)
 this may be because of I ran the secure Linux script as well, any way I can revert all the changes from that script as well.

**Comment by YurinDoctrine** [comment]
You can specify the nvidia driver version so it causes the problem.

**Comment by Loskoss** [comment]
ok will try it and reply soon thanks . another doubt tho  I ran the secure Linux script as well, any way I can revert all the changes from that script as well.

**Comment by YurinDoctrine** [comment]
I don't think secure-linux bricked your system. As I told above this nvidia driver may not compatible with all nvidia systems, so I suggest you to fork this script and change the driver with compatible version of yours...

**Comment by Loskoss** [comment]
thank you so much i understood that nvidia might be the problem. I just want to revert the security script as well
